### ISSUE TITLE
ninject.extensions.wf WebApi and WF4

### ISSUE THREAD

**Issue by songgiang** [ninject/Ninject.Extensions.Wf#1]
I use this extension for my project but how to I register an dependency to workflowapplication. I sign it as Inject properties but it is always a null reference. Could you make a real example for this extension.

**Comment by danielmarbach** [comment]
Hy

You don't need to do anything special but registering your dependencies on the kernel you have. Send me a solution stripped down to your problem and I'll fix it for you

Daniel

Am 01.11.2012 um 05:05 schrieb songgiang notifications@github.com:

**Comment by danielmarbach** [comment]
Btw. here are my blogposts to that topic:

http://www.planetgeek.ch/2010/12/06/dependency-injection-with-windows-workflow-foundation-4-introduction/
http://www.planetgeek.ch/2010/12/09/dependency-injection-with-windows-workflow-foundation-4-an-answer/
http://www.planetgeek.ch/2010/12/10/dependency-injection-with-windows-workflow-foundation-4-advanced/

Daniel

**Comment by songgiang** [comment]
Hi Daniel!

I would like to send you my stripped project via your email. Could you send me your email address?

Best Regards,
Giang

**Comment by danielmarbach** [comment]
Daniel dot marbach at openplace dot net

Am 05.11.2012 um 03:28 schrieb songgiang notifications@github.com:

**Comment by songgiang** [comment]
Thanks Daniel
