### ISSUE TITLE
License Text Refers to Wrong Extension

### ISSUE THREAD

**Issue by airbreather** [ninject/Ninject.Extensions.Wf#2]
From the LICENSE.txt:

> **Ninject.Extensions.Wcf** is intended to be used in both open-source and commercial environments. To allow its use in as many
> situations as possible, **Ninject.Extensions.Wcf** is dual-licensed. You may choose to use **Ninject.Extensions.Wcf** under either the Apache License,
> Version 2.0, or the Microsoft Public License (Ms-PL). These licenses are essentially identical, but you are
> encouraged to evaluate both to determine which best fits your intended use.

The bolded text should say "Ninject.Extensions.Wf".

**Comment by danielmarbach** [comment]
Thanks. I'll fix that. F... Copy paste error

Am 08.03.2013 um 19:30 schrieb airbreather notifications@github.com:
